import java.util.*;
import java.io.*;

// DO NOT EDIT THIS FILE!
// IT MUST WORK UNEDITED 
public class GameDriver
{
	public static void main(String[] args) throws Exception
	{
		// Set the terminal to not require pressing enter.
		// THIS ONLY WORKS ON UNIX!
		// If you want to use Windows use WSL on the VM on LMS
		// https://lms.latrobe.edu.au/mod/forum/discuss.php?d=962672
		String[] cmd = {"/bin/sh", "-c", "stty --file=/dev/tty -icanon -echo"};
		Runtime.getRuntime().exec(cmd).waitFor();
		
		// create the game object.
		GameState game = new GameState();
		
		// Show the map.
		game.renderFrame();
		
		// keep asking for input forever.
		while(true)
		{			
			// read() is a blocking method.
			// It will halt execution untill it recieves input from the user.
			int userInput = System.in.read();	
			
			// notify the game of the user input 
			boolean continueGame = game.onUserInput(userInput);
			if(continueGame == false)
			{
				System.out.println("Thanks for playing");
				break;
			}
			// If the game is finished, show the menu, otherwise tick() the game.		
			if(game.isGameFinished())
				game.showMenu();
			else 
				game.tick();
		}
	}
}
